### ISSUE TITLE
`cost_surface` in data generation vs likelihood

### ISSUE THREAD

**Issue by GatesDupont** [chrissuthy/telemetry-informed-cost#1]
When we simulate the data in `tic_data_generation.R`, we use:

```R
cost_surface <- exp(cost_parameter * landscape^2) # landscape squared
```

But in the likelihood script `scr_tic_likelihood.R`, we use:

```R
cost_surface <- exp(alpha_cost * landscape) # landscape not squared
```

From our last meeting, I think it's supposed to be `landscape^2`.

**Comment by DWLinden** [comment]
This is correct because the squaring is just a trick to get a skewed distribution of cost values.  Really it should be something like this:

`new_landscape <- landscape^2`

Then it signifies that `new_landscape` is the actual landscape we are using for simulation and estimation.

**Comment by GatesDupont** [comment]
Ah, ok, that makes much more sense!
